### PR TITLE
Update CrystalAura.java

### LINKED ISSUE #49: Toggle CrystalAura targeting tracers
I personally find the tracers crystal aura draws from the place block to the target to be kind of annoying, it would be nice if you had the option to toggle them on and off.

### PR DESCRIPTION
**Pull request by UrM0ther**
Closes #49 and #250

### CODE REVIEW

**Comment by S-B99** [comment]
i don't think the last one is a good idea

**Comment by UrM0ther** [comment]
???

**Comment by S-B99** [comment]
the last commit xd.
i'm gonna have to test

**Comment by UrM0ther** [comment]
Ok go ahead

**Pull request merged**
