### PR TITLE
Textradar StrengthDetect

### PR DESCRIPTION
**Pull request by Hamburger2k**
Shows if someone is under the influence of Strength like this: https://imgur.com/a/zVOcxx1 .
Use it if you want idrc. Weakness effect can be added aswell

### CODE REVIEW

**Comment by S-B99** [comment]
Can you please remove the double spaces and unnecessary newlines you added, thanks

**Comment by Hamburger2k** [comment]
Like this? Or do you mean something else, sorry pretty sleepy atm.

**Comment by S-B99** [comment]
ye, that's good thanks

**Comment by S-B99** [comment]
why did you close this tho

**Comment by S-B99** [comment]
I'm waiting to get home so I can merge

**Comment by Hamburger2k** [comment]
User error😳

**Comment by S-B99** [comment]
mfw

**Pull request merged**
