### PR TITLE
probably fixes the crash

### LINKED ISSUE #497: If you die with autotrap on then you get kicked for a null

### PR DESCRIPTION
**Pull request by Vonr**
Closes #497

### CODE REVIEW

**Comment by S-B99** [comment]
This is exactly the solution I had in mind, just waiting for it to build.

**Comment by Vonr** [comment]
oh ok i see guess ill close it the :C jk luv u (cos ur my mom)

**Comment by S-B99** [comment]
no why close
I was waiting for it to build dummy

**Comment by S-B99** [comment]
this is exactly the solution I was gonna do

**Pull request merged**
