### PR TITLE
[+] Add incompatibility message when AntiHunger and Elytrafly are both enabled

### PR DESCRIPTION
**Pull request by hykilpikonna**
image
image

### CODE REVIEW

**Comment by S-B99** [comment]
I already added compatibility in antihunger...

**Comment by S-B99** [comment]
If you look inside the listener you'll see there's already a check

**Comment by S-B99** [comment]
But the getModuleT is just fine if you'd like to make a seperate pull for that.

**Comment by hykilpikonna** [comment]
Oh ya, I didn't see that, oops! 🤦‍♀

**Comment by S-B99** [comment]
All good lol.

**Pull request closed without merging**
