### PR TITLE
Breaking Warning

### PR DESCRIPTION
**Pull request by Antonio32A**
This module shows a warning on you screen when somebody is breaking blocks near you.

Options:
    - Min Range: The minimum range of the block being broken to you to trigger the warning. Example: 1.5 = the blocks next to your feet.
    - Obsidian Only: Only trigger the warning if the block is obsidian.
    - Pickaxe Only: Only trigger the warning if the breaker is using a pickaxe.

### CODE REVIEW

**Comment by S-B99** [comment]
Yea, I was looking for it on ForgeHax's repo but I couldn't find which file it was

**Comment by Antonio32A** [comment]
Oh right sorry, forgot to do that. I originally coded this for forgehax and just wanted to rewrite it and improve it for kami blue.

**Comment by S-B99** [comment]
Ye, can you link the file that it's in forgehax?

**Comment by Antonio32A** [comment]
> Ye, can you link the file that it's in forgehax?

https://github.com/fr1kin/ForgeHax/blob/20117406c02ac3da85da91eaad7418a78ca84c35/src/main/java/com/matt/forgehax/mods/CoordsFinder.java#L126

**Comment by S-B99** [comment]
thanks

**Pull request merged**
