### PR TITLE
added aliases to commands

### LINKED ISSUE #358: Command aliases
Reopened due to the autocomplete not working and me being unable to fix that

### PR DESCRIPTION
**Pull request by Tigermouthbear**
Reimplements #373, closes #358 
 
Added aliases and aliases auto completions 😄

### CODE REVIEW

**Comment by Vonr** [comment]
why does this use atomic booleans?

**Comment by cookiedragon234** [comment]
This is epic!!! Thank you tiger!?’bbb!

*Btw the currentFillinLine assignment line is pretty horrible lol might wanna fix that.*

Thanks tiger!!!!’n

@Vonr gotta have thread safety

**Comment by S-B99** [comment]
Why are you using scala for arrays, and if the project doesn't have it why is it imported?

**Comment by Tigermouthbear** [comment]
Oh, well I didn't know Arrays was in java.util

**Comment by S-B99** [comment]
what a bruh moment

fix plox

**Comment by S-B99** [comment]
I disabled commit signing for now but in the future please sign your commits, not just for this repo but it's way safer so nobody can impersonate your commits.

**Comment by cookiedragon234** [comment]
Yeah remember to remove scala from your intellij autoimport. java.awt.List is another similar offender.

**Comment by S-B99** [comment]
smh not using autoimporter

i'll fix it up when merging locally probably. 

> Btw the currentFillinLine assignment line is pretty horrible lol might wanna fix that.

which line is that @cookiedragon234 ?

**Comment by S-B99** [comment]
Edit: found it 

Yea I really wanna split that up into multiple lines

**Comment by S-B99** [comment]
I *think* i have permission to edit tiger's branch so I'll do it later today

**Comment by S-B99** [comment]
that looks way better, thanks. I want to finish up my local stuff and then i'll merge it

**Comment by Tigermouthbear** [comment]
np, I forgot to remove the import tho :(

**Comment by S-B99** [comment]
can you remove that, and the comment? just press `ctrl alt o` in intellij

**Comment by S-B99** [comment]
or it's `ctrl shift o`, can't remember

**Comment by Tigermouthbear** [comment]
sure

**Comment by S-B99** [comment]
epic, thakns

**Pull request merged**
