### PR TITLE
Class lookup (move #303 to refactored branch)

### LINKED ISSUE #295: ModuleManager lookup by class, not name

### PR DESCRIPTION
**Pull request by S-B99**
Closes #295

### CODE REVIEW

**Comment by S-B99** [comment]
aaaaarmeinder to myself that i have to do this myself

**Comment by S-B99** [comment]
Oof this branch is going to need to be completely recreated I think

**Comment by S-B99** [comment]
@cookiedragon234 could you please take a look at this? Even before I fixed all the merge conflicts, the `class-lookup` branch didn't launch, with the same error as it currently does.
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.kami.json:MixinAbstractClientPlayer] from phase [DEFAULT] in config [mixins.kami.json] FAILED during PREPARE
```
```
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.kami.json:MixinAbstractClientPlayer target net.minecraft.client.entity.AbstractClientPlayer was already transformed.
```
@EmotionalLove aaaa I finally got around to merging this and it doesn't work, nor does it before I fixed merge conflicts smh

**Comment by cookiedragon234** [comment]
Sounds like you have multiple mixins. Maybe there are multiple classes that target the same class in the Mixin annotation, or you referenced a class twice in the mixins.whatever.json @S-B99

**Comment by S-B99** [comment]
Talked to cookie on discord, I don't have duplicate @ Mixin annotations anywhere, nor duplicate mixin registers in `mixins.kami.json`

I created an issue in the Mixin GitHub here: SpongePowered/Mixin/issues/388

**Comment by Vonr** [comment]
omg cookiedragon is alive???

**Comment by cookiedragon234** [comment]
@vonr no

**Comment by S-B99** [comment]
Fixed, merging later today.

**Comment by S-B99** [comment]
Waiting for #521 to merge

**Pull request merged**
