### PR TITLE
ED the standard text editor

### PR DESCRIPTION
**Pull request by RedTechEngineer**
A fully functioning™️ implementation of ED for kami blue

p.s. if you reject this merge i'll cri irl

### CODE REVIEW

**Comment by RedTechEngineer** [comment]
> Ed, man! !man ed

?

**Comment by S-B99** [comment]
> ?

it's in the comment

**Comment by RedTechEngineer** [comment]
> > ?
> 
> it's in the comment

?

**Comment by S-B99** [comment]
2020-02-25-223426_361x188_scrot

**Comment by RedTechEngineer** [comment]
ed

**Comment by S-B99** [comment]
I appreciate the pr but 99% of the userbase is dumb and would complain there is a useless module, also it is sort of useless beyond the meme <3

**Pull request closed without merging**
