### PR TITLE
[kamiblue-588] Code cleanup

### LINKED ISSUE #588: Use a consistent coding style and refactor existing code to fit it
Todo
- [x] exclude idea formatting settings from gitignore 

To consider
- [x] 4 tab indentation with spaces
- [x] space before and after () 
- [x] break up annotations (eg module annotations)

### PR DESCRIPTION
**Pull request by GenericException**
## Issues resolved

* Closes #588

### CODE REVIEW

**Comment by S-B99** [comment]
who are you and why do all the cool kids know you 🧐

**Comment by S-B99** [comment]
If you'd like this to be merged, your commits need to be signed.

**Comment by Vonr** [comment]
what the frick is the point of this.

**Comment by S-B99** [comment]
big meme

**Comment by Vonr** [comment]
List of changes:
removed donating links and related
gitignored everything
fucked travis

**Comment by cookiedragon234** [comment]
@S-B99 Im signing it off for him, feel free to merge

**Comment by S-B99** [comment]
xdddd

**Pull request closed without merging**
