### PR TITLE
Feature/offhandgap#356

### LINKED ISSUE #356: Offhand Gap (Toggle gap with key or right clicking mouse)
Replaces your totem with a _gapple_ while holding right click

### PR DESCRIPTION
**Pull request by S-B99**
Closes #356 

Atm waiting on 

- [x] disabling when you stop eating, 
- [x] option to disable sword check
otherwise ready to merge

### CODE REVIEW

**Comment by S-B99** [comment]
```java
            if (entity == mc.player || ((EntityLivingBase) entity).getHealth() <= 0) {
                continue;
            }
```
for ref

**Comment by pol-y-mer** [comment]
Working on sword check option and disable when not eating

**Comment by Vonr** [comment]
look at you, already better than me with my 2 years of experience in coding bad java

**Comment by S-B99** [comment]
polymer is smart uwu

**Comment by Vonr** [comment]
yeah you should probably revoke my repo access and give it to him :/

**Comment by Vonr** [comment]
im not using it much anyway

**Comment by Vonr** [comment]
or, if it doesnt violate github tos, make a bot that keeps 2 mirrored repos up to date with each other

**Comment by S-B99** [comment]
is ok <3
you helped out with stuff too

**Comment by Vonr** [comment]
then make 3, 4, 5, 6 kami blue repos

**Comment by S-B99** [comment]
that's what people having forks is

**Comment by Vonr** [comment]
the actual repo has jenkins though

**Comment by S-B99** [comment]
idk what that is
this is off topic anyways

**Comment by pol-y-mer** [comment]
bro what lol i wasnt tracking <3 love u guys

**Comment by pol-y-mer** [comment]
lmaooo im in class and my pc started screammmmmming because i accidentally created a loop :flushed:

**Comment by S-B99** [comment]
literally me 😳😳

**Pull request merged**
